# Generated by Django 4.2 on 2023-04-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="aaa", max_length=50)),
                ("phone_number", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Good",
            fields=[
                (
                    "goods_name",
                    models.CharField(
                        max_length=35, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "goods_type",
                    models.CharField(
                        choices=[("G", "Goods"), ("S", "Services")], max_length=1
                    ),
                ),
                ("rat", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "goods_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="addForms.good"
                    ),
                ),
                (
                    "name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addForms.client",
                    ),
                ),
            ],
        ),
    ]
