# Generated by Django 4.2 on 2023-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addForms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="goods_type",
            field=models.CharField(
                choices=[("G", "Товар"), ("S", "Услуга")], max_length=1
            ),
        ),
    ]
