# Generated by Django 4.2 on 2023-05-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addForms", "0002_alter_good_goods_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="good",
            name="goods_name",
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
