# Generated by Django 4.2 on 2023-05-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addForms", "0003_good_id_alter_good_goods_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="good", name="id",),
        migrations.AlterField(
            model_name="good",
            name="goods_name",
            field=models.CharField(
                max_length=35, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
